production:
#  searchd_file_path: "/var/www/latest_web20_craze/shared/sphinx"
#  port: 9312
#  config_file: "RAILS_ROOT/config/ENVIRONMENT.sphinx.conf"
#  searchd_log_file: "RAILS_ROOT/log/searchd.log"
#  query_log_file: "RAILS_ROOT/log/searchd.query.log"
#  pid_file: "RAILS_ROOT/log/searchd.ENVIRONMENT.pid"
#  address: 10.0.0.4
#  mem_limit: 128M
#  morphology: stem_en
#  for more info - http://freelancing-god.github.com/ts/en/advanced_config.html

  max_matches: 50
  
  enable_star: true
#  min_prefix_len: 3
#  prefix_fields: name, title
  min_infix_len: 3
  infix_fields: title, body

development:
  max_matches: 50

  enable_star: true
#  min_prefix_len: 3
#  prefix_fields: name, title
  min_infix_len: 3
  infix_fields: title, body
